### PR TITLE
updated .sql file to create table and insert rows

### PR DESCRIPTION
**Pull request by xJeris**
Moved old .sql file to a new 'Archive' folder so our previous steps aren't lost.
Created new .sql file that creates the db table and inserts data.
fixed a typo in .sql file.

### CODE REVIEW

**Review by jpharvey8 — APPROVED** [review]
Approved

**Review by dtrefsgar — APPROVED** [review]
approved

**Review by awar2170 — APPROVED** [review]
Approved, thanks for the good work!

**Review by bberry91221 — APPROVED** [review]
Approved.

**Pull request merged**
